import RegisterModal from "./components/modals/RegisterModal";
import Sidebar from "./components/nav/Sidebar";
import "./globals.css";
import { Nunito } from "next/font/google";

import ToasterProvider from "../app/providers/ToastProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import ProductModal from "./components/modals/ProductModal";

export const metadata = {
  title: "Ecommerce Admin",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <LoginModal />
        <RegisterModal />
        <ProductModal />
        <div className="h-screen bg-blue-900">
          <div className="pl-12 lg:pl-48 mx-auto h-full w-full">
            <div className="grid h-full grid-cols-12">
              <Sidebar currentUser={currentUser} />
              <div className="col-span-11 border-x-[1px] border-neutral-800">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
